GET http://localhost:3000/api/users/15 HTTP/1.1

###

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "name": "Tatiana",
    "age": 26
}

###

DELETE  http://localhost:3000/api/users/15 HTTP/1.1

###

PUT http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "id": 5,
    "name": "sample",
    "age": 1
}
